const servicePagesSet = [
    {
        heading: "Výkopové práce",
        url: "/sluzby/vykopove-prace",
        src: [
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-1.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-2.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-3.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-4.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-5.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-6.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-7.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-8.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-9.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-10.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-11.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-12.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-13.jpg",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-14.jpg",
        ],
        alt: "Služba výkopové práce - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Stavební a zámečnické konstrukce",
        url: "/sluzby/stavebni-a-zamecnicke-kontrukce",
        src: [
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-1.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-2.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-3.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-4.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-5.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-6.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-7.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-8.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-9.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-10.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-11.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-12.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-13.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-14.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-15.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-16.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-17.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-18.jpg",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-19.jpg"
        ],
        alt: "Služba stavební a zamečnické konstrukce - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Společné prostory bytových prostorů",
        url: "/sluzby/spolecne-prostory-bytovych-domu",
        src: [
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-1.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-2.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-3.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-4.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-5.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-6.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-7.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-8.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-9.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-10.jpg",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-11.jpg"
        ],
        alt: "Služba společné prostory bytových prostorů - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Rekonstrukce a odizolování základů a kanalizace",
        url: "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace",
        src: [
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-1.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-2.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-3.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-4.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-5.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-6.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-7.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-8.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-9.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-10.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-11.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-12.jpg",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-13.jpg",
        ],
        alt: "Služba rekonstrukce a odizolování základů a kanalizace - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Rekonstrukce fasád a lodžií",
        url: "/sluzby/rekonstrukce-fasad-a-lodzii",
        src: [
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-1.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-2.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-3.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-4.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-5.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-6.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-7.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-8.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-9.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-10.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-11.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-12.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-13.jpg",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-14.jpg",
        ],
        alt: "Služba rekonstrukce fasád a lodžií - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Rekonstrukce sociálních bytů",
        url: "/sluzby/rekonstrukce-socialnich-bytu",
        src: [
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-1.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-2.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-3.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-4.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-5.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-6.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-7.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-8.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-9.jpg",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-10.jpg",
        ],
        alt: "Služba rekonstrukce sociálních bytů - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Ploty a terasy",
        url: "/sluzby/ploty-a-terasy",
        src: [
            "/sluzby/ploty-a-terasy/ploty-a-terasy-1.jpg",
            "/sluzby/ploty-a-terasy/ploty-a-terasy-2.jpg",
            "/sluzby/ploty-a-terasy/ploty-a-terasy-3.jpg",
        ],
        alt: "Služba ploty a terasy - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Koupelny",
        url: "/sluzby/koupelny",
        src: [
            "/sluzby/koupelny/koupelny-1.avif",
            "/sluzby/koupelny/koupelny-2.avif",
            "/sluzby/koupelny/koupelny-3.avif",
            "/sluzby/koupelny/koupelny-4.avif",
            "/sluzby/koupelny/koupelny-5.avif",
            "/sluzby/koupelny/koupelny-6.avif",
            "/sluzby/koupelny/koupelny-7.avif",
            "/sluzby/koupelny/koupelny-8.avif",
            "/sluzby/koupelny/koupelny-9.avif",
            "/sluzby/koupelny/koupelny-10.avif",
            "/sluzby/koupelny/koupelny-11.avif",
        ],
        alt: "Služba koupelny - Jinex.cz | Jiří Nesměrák"
    },
];

export default servicePagesSet;