const servicePagesSet = [
    {
        heading: "Výkopové práce",
        url: "/sluzby/vykopove-prace",
        src: [
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-1.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-2.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-3.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-4.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-5.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-6.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-7.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-8.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-9.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-10.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-11.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-12.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-13.avif",
            "/sluzby/vykopove-prace/vykopove-prace/vykopove-prace/vykopove-prace-14.avif",
        ],
        alt: "Služba výkopové práce - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Stavební a zámečnické konstrukce",
        url: "/sluzby/stavebni-a-zamecnicke-kontrukce",
        src: [
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-1.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-2.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-3.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-4.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-5.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-6.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-7.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-8.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-9.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-10.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-11.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-12.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-13.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-14.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-15.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-16.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-17.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-18.avif",
            "/sluzby/stavebni-a-zamecnicke-kontrukce/stavebni-a-zamecnicke-konstrukce-19.avif"
        ],
        alt: "Služba stavební a zamečnické konstrukce - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Společné prostory bytových prostorů",
        url: "/sluzby/spolecne-prostory-bytovych-domu",
        src: [
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-1.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-2.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-3.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-4.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-5.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-6.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-7.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-8.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-9.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-10.avif",
            "/sluzby/spolecne-prostory-bytovych-domu/spolecne-prostory-bytovych-prostoru-11.avif"
        ],
        alt: "Služba společné prostory bytových prostorů - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Rekonstrukce a odizolování základů a kanalizace",
        url: "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace",
        src: [
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-1.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-2.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-3.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-4.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-5.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-6.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-7.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-8.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-9.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-10.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-11.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-12.avif",
            "/sluzby/rekonstrukce-a-odizolovani-zakladu-a-kanalizace/rekonstrukce-a-odizolovani-zakladu-a-kanalizace-13.avif",
        ],
        alt: "Služba rekonstrukce a odizolování základů a kanalizace - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Rekonstrukce fasád a lodžií",
        url: "/sluzby/rekonstrukce-fasad-a-lodzii",
        src: [
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-1.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-2.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-3.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-4.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-5.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-6.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-7.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-8.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-9.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-10.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-11.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-12.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-13.avif",
            "/sluzby/rekonstrukce-fasad-a-lodzii/rekonstrukce-fasad-a-lodzii-14.avif",
        ],
        alt: "Služba rekonstrukce fasád a lodžií - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Rekonstrukce sociálních bytů",
        url: "/sluzby/rekonstrukce-socialnich-bytu",
        src: [
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-1.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-2.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-3.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-4.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-5.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-6.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-7.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-8.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-9.avif",
            "/sluzby/rekonstrukce-socialnich-bytu/rekonstrukce-socialnich-bytu-10.avif",
        ],
        alt: "Služba rekonstrukce sociálních bytů - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Ploty a terasy",
        url: "/sluzby/ploty-a-terasy",
        src: [
            "/sluzby/ploty-a-terasy/ploty-a-terasy-1.avif",
            "/sluzby/ploty-a-terasy/ploty-a-terasy-2.avif",
            "/sluzby/ploty-a-terasy/ploty-a-terasy-3.avif",
        ],
        alt: "Služba ploty a terasy - Jinex.cz | Jiří Nesměrák"
    },
    {
        heading: "Koupelny",
        url: "/sluzby/koupelny",
        src: [
            "/sluzby/koupelny/koupelny-1.avif",
            "/sluzby/koupelny/koupelny-2.avif",
            "/sluzby/koupelny/koupelny-3.avif",
            "/sluzby/koupelny/koupelny-4.avif",
            "/sluzby/koupelny/koupelny-5.avif",
            "/sluzby/koupelny/koupelny-6.avif",
            "/sluzby/koupelny/koupelny-7.avif",
            "/sluzby/koupelny/koupelny-8.avif",
            "/sluzby/koupelny/koupelny-9.avif",
            "/sluzby/koupelny/koupelny-10.avif",
            "/sluzby/koupelny/koupelny-11.avif",
        ],
        alt: "Služba koupelny - Jinex.cz | Jiří Nesměrák"
    },
];

export default servicePagesSet;